// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlstore

type Collection struct {
	Colid int64
	Name  string
}

type InternalDbSettingsInt struct {
	Name  string
	Value int64
}

type Object struct {
	Uid             interface{}
	Colid           int64
	Oid             string
	Content         []byte
	Seq             int64
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
	DbEpoch         int64
}

type VwObject struct {
	Uid             interface{}
	Oid             string
	Collection      string
	Content         []byte
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
	DbEpoch         int64
	Colid           int64
}
