// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlstore

type Collection struct {
	Colid int64
	Name  string
}

type KeyPath struct {
	Colid  int64
	Path   string
	ValUid []byte
}

type KeyValHistory struct {
	Colid        int64
	ValUid       []byte
	ParentValUid []byte
}

type KeyValue struct {
	Colid      int64
	ValUid     []byte
	Generation int64
	Content    []byte
}

type Viewkeyvalue struct {
	Colid      int64
	Path       string
	ValUid     []byte
	Content    []byte
	Generation int64
}
