// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlstore

import (
	"context"
)

const getCollectionIDByName = `-- name: GetCollectionIDByName :one
select c.colid
from collections c
where name = ?
limit 1
`

func (q *Queries) GetCollectionIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCollectionIDByName, name)
	var colid int64
	err := row.Scan(&colid)
	return colid, err
}

const getIntSetting = `-- name: GetIntSetting :one
select value from _internal_db_settings_int
where name = ?
limit 1
`

func (q *Queries) GetIntSetting(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIntSetting, name)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getObject = `-- name: GetObject :one
select content
from objects
where oid = ? and colid = ?
`

type GetObjectParams struct {
	Oid   string
	Colid int64
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getObject, arg.Oid, arg.Colid)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const getObjectByCollection = `-- name: GetObjectByCollection :one
select content
from vw_objects
where oid = ? and collection = ?
`

type GetObjectByCollectionParams struct {
	Oid        string
	Collection string
}

func (q *Queries) GetObjectByCollection(ctx context.Context, arg GetObjectByCollectionParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getObjectByCollection, arg.Oid, arg.Collection)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const putObject = `-- name: PutObject :exec
insert into objects (uid, oid, colid, content, updated_at_unixms, created_at_unixms, db_epoch)
values (?, ?, ?, ?, ?, ?, ?)
on conflict (oid, colid) do
update
set content = excluded.content,
    updated_at_unixms = excluded.updated_at_unixms,
    db_epoch = excluded.db_epoch
`

type PutObjectParams struct {
	Uid             interface{}
	Oid             string
	Colid           int64
	Content         []byte
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
	DbEpoch         int64
}

func (q *Queries) PutObject(ctx context.Context, arg PutObjectParams) error {
	_, err := q.db.ExecContext(ctx, putObject,
		arg.Uid,
		arg.Oid,
		arg.Colid,
		arg.Content,
		arg.UpdatedAtUnixms,
		arg.CreatedAtUnixms,
		arg.DbEpoch,
	)
	return err
}

const setIntSetting = `-- name: SetIntSetting :exec
insert into _internal_db_settings_int(name, value)
values (?, ?)
on conflict (name) do
update 
set value = excluded.value
`

type SetIntSettingParams struct {
	Name  string
	Value int64
}

func (q *Queries) SetIntSetting(ctx context.Context, arg SetIntSettingParams) error {
	_, err := q.db.ExecContext(ctx, setIntSetting, arg.Name, arg.Value)
	return err
}

const upsertCollection = `-- name: UpsertCollection :one
insert into collections(name)
values (?) on conflict (name) do
update
set name = excluded.name
returning colid
`

func (q *Queries) UpsertCollection(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCollection, name)
	var colid int64
	err := row.Scan(&colid)
	return colid, err
}
