// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlstore

import (
	"context"
)

const getCollectionIDByName = `-- name: GetCollectionIDByName :one
select c.colid
from collections c
where name = ?
limit 1
`

func (q *Queries) GetCollectionIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCollectionIDByName, name)
	var colid int64
	err := row.Scan(&colid)
	return colid, err
}

const getIntSetting = `-- name: GetIntSetting :one
select value from _internal_db_settings_int
where name = ?
limit 1
`

func (q *Queries) GetIntSetting(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIntSetting, name)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getObjectSeq = `-- name: GetObjectSeq :one
select content, seq, updated_at_unixms, created_at_unixms
from objects
where oid = ? and colid = ?
`

type GetObjectSeqParams struct {
	Oid   string
	Colid int64
}

type GetObjectSeqRow struct {
	Content         []byte
	Seq             int64
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
}

func (q *Queries) GetObjectSeq(ctx context.Context, arg GetObjectSeqParams) (GetObjectSeqRow, error) {
	row := q.db.QueryRowContext(ctx, getObjectSeq, arg.Oid, arg.Colid)
	var i GetObjectSeqRow
	err := row.Scan(
		&i.Content,
		&i.Seq,
		&i.UpdatedAtUnixms,
		&i.CreatedAtUnixms,
	)
	return i, err
}

const putNew = `-- name: PutNew :exec
insert into objects (uid, oid, colid, content, updated_at_unixms, created_at_unixms, db_epoch, seq)
values (?, ?, ?, ?, ?, ?, ?, 1)
`

type PutNewParams struct {
	Uid             interface{}
	Oid             string
	Colid           int64
	Content         []byte
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
	DbEpoch         int64
}

func (q *Queries) PutNew(ctx context.Context, arg PutNewParams) error {
	_, err := q.db.ExecContext(ctx, putNew,
		arg.Uid,
		arg.Oid,
		arg.Colid,
		arg.Content,
		arg.UpdatedAtUnixms,
		arg.CreatedAtUnixms,
		arg.DbEpoch,
	)
	return err
}

const putObjectSeq = `-- name: PutObjectSeq :one
insert into objects (uid, oid, colid, content, updated_at_unixms, created_at_unixms, db_epoch, seq)
values (?, ?, ?, ?, ?, ?, ?, 1)
on conflict (oid, colid) do
update
set content = excluded.content,
    updated_at_unixms = excluded.updated_at_unixms,
    db_epoch = excluded.db_epoch,
    seq = seq + 1
returning seq
`

type PutObjectSeqParams struct {
	Uid             interface{}
	Oid             string
	Colid           int64
	Content         []byte
	UpdatedAtUnixms int64
	CreatedAtUnixms int64
	DbEpoch         int64
}

func (q *Queries) PutObjectSeq(ctx context.Context, arg PutObjectSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putObjectSeq,
		arg.Uid,
		arg.Oid,
		arg.Colid,
		arg.Content,
		arg.UpdatedAtUnixms,
		arg.CreatedAtUnixms,
		arg.DbEpoch,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const setIntSetting = `-- name: SetIntSetting :exec
insert into _internal_db_settings_int(name, value)
values (?, ?)
on conflict (name) do
update 
set value = excluded.value
`

type SetIntSettingParams struct {
	Name  string
	Value int64
}

func (q *Queries) SetIntSetting(ctx context.Context, arg SetIntSettingParams) error {
	_, err := q.db.ExecContext(ctx, setIntSetting, arg.Name, arg.Value)
	return err
}

const updateObject = `-- name: UpdateObject :execrows
update objects
set content = ?,
    updated_at_unixms = ?,
    db_epoch = ?,
    seq = seq + 1
where
    oid = ?
    and colid = ?
    and seq = ?
`

type UpdateObjectParams struct {
	Content         []byte
	UpdatedAtUnixms int64
	DbEpoch         int64
	Oid             string
	Colid           int64
	Seq             int64
}

func (q *Queries) UpdateObject(ctx context.Context, arg UpdateObjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateObject,
		arg.Content,
		arg.UpdatedAtUnixms,
		arg.DbEpoch,
		arg.Oid,
		arg.Colid,
		arg.Seq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCollection = `-- name: UpsertCollection :one
insert into collections(name)
values (?) on conflict (name) do
update
set name = excluded.name
returning colid
`

func (q *Queries) UpsertCollection(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCollection, name)
	var colid int64
	err := row.Scan(&colid)
	return colid, err
}
