// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlstore

import (
	"context"
)

const getValue = `-- name: GetValue :one
select colid, path, val_uid, content, generation
from viewkeyvalue
where path = ? and colid = ?
limit 1
`

type GetValueParams struct {
	Path  string
	Colid int64
}

func (q *Queries) GetValue(ctx context.Context, arg GetValueParams) (Viewkeyvalue, error) {
	row := q.db.QueryRowContext(ctx, getValue, arg.Path, arg.Colid)
	var i Viewkeyvalue
	err := row.Scan(
		&i.Colid,
		&i.Path,
		&i.ValUid,
		&i.Content,
		&i.Generation,
	)
	return i, err
}

const putKey = `-- name: PutKey :exec
insert into key_paths (colid, path, val_uid)
values (?, ?, ?)
on conflict (colid, path)
do update set val_uid = excluded.val_uid
`

type PutKeyParams struct {
	Colid  int64
	Path   string
	ValUid []byte
}

func (q *Queries) PutKey(ctx context.Context, arg PutKeyParams) error {
	_, err := q.db.ExecContext(ctx, putKey, arg.Colid, arg.Path, arg.ValUid)
	return err
}

const putValue = `-- name: PutValue :exec
insert into key_values (colid, val_uid, content, generation)
values (?, ?, ?, ?)
`

type PutValueParams struct {
	Colid      int64
	ValUid     []byte
	Content    []byte
	Generation int64
}

func (q *Queries) PutValue(ctx context.Context, arg PutValueParams) error {
	_, err := q.db.ExecContext(ctx, putValue,
		arg.Colid,
		arg.ValUid,
		arg.Content,
		arg.Generation,
	)
	return err
}

const putValueHistory = `-- name: PutValueHistory :exec
insert into key_val_history(colid, val_uid, parent_val_uid)
values (?, ?, ?)
`

type PutValueHistoryParams struct {
	Colid        int64
	ValUid       []byte
	ParentValUid []byte
}

func (q *Queries) PutValueHistory(ctx context.Context, arg PutValueHistoryParams) error {
	_, err := q.db.ExecContext(ctx, putValueHistory, arg.Colid, arg.ValUid, arg.ParentValUid)
	return err
}

const upsertCollection = `-- name: UpsertCollection :one
insert into collections(name)
values (?) on conflict (name) do
update
set name = excluded.name
returning colid
`

func (q *Queries) UpsertCollection(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCollection, name)
	var colid int64
	err := row.Scan(&colid)
	return colid, err
}
